const divyaDesamData = [
  {
    "id": "DD001",
    "name_ta": "திருவரங்கம்",
    "name_en": "Srirangam Ranganathaswamy Temple",
    "district": "Tiruchirappalli",
    "location": "Srirangam",
    "god": "Ranganathar",
    "goddess": "Ranganayaki",
    "history": "108 திவ்ய தேசங்களில் முதன்மையானது. பூலோக வைகுண்டம். 7 பிரகாரங்கள் மற்றும் 21 கோபுரங்களைக் கொண்டது.",
    "travel": "திருச்சி பேருந்து நிலையத்திலிருந்து 10 கி.மீ. சிறப்பு தரிசனக் கட்டணம் ரூ.50 மற்றும் ரூ.250 (தற்போது மாறுபடலாம்). காலை 7 மணி முதல் 11 மணி வரை தரிசனத்திற்குச் சிறந்த நேரம்."
  },
  {
    "id": "DD002",
    "name_ta": "திருக்கோழி (உறையூர்)",
    "name_en": "Thirukkozhi (Uraiyur)",
    "district": "Tiruchirappalli",
    "location": "Uraiyur",
    "god": "Azhagiya Manavalan",
    "goddess": "Kamalavalli",
    "history": "சோழ மன்னனின் மகளாகப் பிறந்த கமலவல்லி நாச்சியாரை ரங்கநாதர் மணம் புரிந்த தலம். திருப்பாணாழ்வார் அவதரித்த இடம்.",
    "travel": "திருச்சி பேருந்து நிலையத்திலிருந்து 6 கி.மீ. ஸ்ரீரங்கத்திலிருந்து 8 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD003",
    "name_ta": "திருக்கரம்பனூர்",
    "name_en": "Thirukkarambanur (Uthamar Kovil)",
    "district": "Tiruchirappalli",
    "location": "Uthamar Kovil",
    "god": "Purushottaman",
    "goddess": "Poorna Valli",
    "history": "மும்மூர்த்தி தலம். சிவன், விஷ்ணு, பிரம்மா மூவருக்கும் தனி சன்னதிகள் உள்ளன. கதம்ப முனிவருக்கு இறைவன் காட்சி தந்த இடம்.",
    "travel": "திருச்சியிலிருந்து 14 கி.மீ; ஸ்ரீரங்கத்திலிருந்து 5 கி.மீ. திருச்சி-சென்னை நெடுஞ்சாலையில் உள்ளது."
  },
  {
    "id": "DD004",
    "name_ta": "திருவெள்ளறை",
    "name_en": "Thiruvellarai Pundarikakshan",
    "district": "Tiruchirappalli",
    "location": "Thiruvellarai",
    "god": "Pundarikakshan",
    "goddess": "Pankayavalli",
    "history": "ஸ்ரீரங்கத்தை விடப் பழமையான கோயில். சிபி சக்கரவர்த்தியால் கட்டப்பட்டது. இங்கு 18 படிகள் கீதையின் 18 அத்தியாயங்களைக் குறிக்கின்றன.",
    "travel": "திருச்சியிலிருந்து 27 கி.மீ. திருச்சி-துறையூர் சாலையில் அமைந்துள்ளது."
  },
  {
    "id": "DD005",
    "name_ta": "திருஅன்பில்",
    "name_en": "Thiruanbil Sundararaja Perumal",
    "district": "Tiruchirappalli",
    "location": "Anbil",
    "god": "Sundararajan",
    "goddess": "Azhagiyavalli",
    "history": "பிரம்மா மற்றும் வால்மீகிக்கு இறைவன் காட்சி தந்த இடம். கொள்ளிடம் ஆற்றின் கரையில் அமைந்துள்ளது.",
    "travel": "திருச்சியிலிருந்து 30 கி.மீ. லால்குடி வழியாகச் செல்ல வேண்டும். கொள்ளிடம் ஆற்றைக் கடந்து செல்ல வேண்டும்."
  },
  {
    "id": "DD006",
    "name_ta": "திருப்பேர்நகர்",
    "name_en": "Thirupper Nagar (Koviladi)",
    "district": "Thanjavur",
    "location": "Koviladi",
    "god": "Appakkudathaan",
    "goddess": "Indra Valli",
    "history": "உபமன்யு முனிவருக்கு இறைவன் அப்பக் குடத்துடன் காட்சி தந்து பசி ஆற்றிய தலம்.",
    "travel": "திருச்சியிலிருந்து 25 கி.மீ. கல்லணை வழியாகத் தஞ்சாவூர் செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD007",
    "name_ta": "திருக்கண்டியூர்",
    "name_en": "Thirukkandiyur",
    "district": "Thanjavur",
    "location": "Kandiyur",
    "god": "Hara Saabha Vimocchanar",
    "goddess": "Kamalavalli",
    "history": "சிவபெருமானின் பிரம்மஹத்தி தோஷம் நீங்கிய தலம். திரிமூர்த்தி தலம்.",
    "travel": "தஞ்சாவூரிலிருந்து 10 கி.மீ. திருவையாறு செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD008",
    "name_ta": "திருக்கூடலூர்",
    "name_en": "Thirukkoodalur",
    "district": "Thanjavur",
    "location": "Aduthurai Perumal Koil",
    "god": "Vaiyam Kaatha Perumal",
    "goddess": "Padmasani",
    "history": "காவேரி, கொள்ளிடம் மற்றும் அமிர்த புஷ்கரிணி ஆகிய மூன்று நதிகள் கூடும் இடம்.",
    "travel": "தஞ்சாவூரிலிருந்து 22 கி.மீ. திருவையாறு - கும்பகோணம் சாலையில் உள்ளது."
  },
  {
    "id": "DD009",
    "name_ta": "திருக்கவித்தலம்",
    "name_en": "Thirukkavithalam (Kabisthalam)",
    "district": "Thanjavur",
    "location": "Kabisthalam",
    "god": "Gajendra Varadhar",
    "goddess": "Ramamanivalli",
    "history": "கஜேந்திர யானைக்கு இறைவன் மோட்சம் அளித்த தலம். ஆஞ்சநேயருக்கு இறைவன் காட்சி தந்த இடம்.",
    "travel": "கும்பகோணத்திலிருந்து 15 கி.மீ. திருவையாறு செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD010",
    "name_ta": "திருப்புள்ளம்பூதங்குடி",
    "name_en": "Thiruppullabhoothangudi",
    "district": "Thanjavur",
    "location": "Pullabhoothangudi",
    "god": "Valvil Raman",
    "goddess": "Potramaraiyal",
    "history": "ஜடாயுவுக்கு ராமபிரான் இறுதிச் சடங்கு செய்த தலம். ராமன் சயன கோலத்தில் இருக்கும் அபூர்வ தலம்.",
    "travel": "கும்பகோணத்திலிருந்து 12 கி.மீ. சுவாமிமலைக்கு அருகில் உள்ளது."
  },
  {
    "id": "DD011",
    "name_ta": "திருஆதனூர்",
    "name_en": "Thiru Adhanur",
    "district": "Thanjavur",
    "location": "Adhanur",
    "god": "Aandu Alakkum Ayyan",
    "goddess": "Ranganayaki",
    "history": "காமதேனு வழிப்பட்ட தலம். இறைவன் கையில் எழுத்தாணி மற்றும் ஏடு ஏந்தி காட்சி தருகிறார்.",
    "travel": "சுவாமிமலையிலிருந்து 3 கி.மீ தொலைவில் உள்ளது."
  },
  {
    "id": "DD012",
    "name_ta": "திருக்குடந்தை",
    "name_en": "Thirukudanthai (Kumbakonam)",
    "district": "Thanjavur",
    "location": "Kumbakonam",
    "god": "Aaravamuthan",
    "goddess": "Komalavalli",
    "history": "பெரிய ஆறுகளுக்கு நடுவே கலசத்தில் தங்கிய இறைவன். நாலாயிர திவ்ய பிரபந்தம் மீட்கப்படக் காரணமான தலம்.",
    "travel": "கும்பகோணம் நகரின் மையப்பகுதியில் அமைந்துள்ளது."
  },
  {
    "id": "DD013",
    "name_ta": "திருவிண்ணகர்",
    "name_en": "Thiruvinnagar (Oppiliappan)",
    "district": "Thanjavur",
    "location": "Oppiliappan Kovil",
    "god": "Uppiliappan",
    "goddess": "Bhoomadevi",
    "history": "இங்கு இறைவனுக்கு உப்பு இல்லாத நிவேதனமே வழங்கப்படுகிறது. 'தன்னொப்பாரில்லாதவன்' என்பதால் ஒப்பிலியப்பன்.",
    "travel": "கும்பகோணத்திலிருந்து 7 கி.மீ. திருநாகேஸ்வரத்திற்கு அருகில் உள்ளது."
  },
  {
    "id": "DD014",
    "name_ta": "திருநறையூர்",
    "name_en": "Thirunaraiyur (Nachiar Koil)",
    "district": "Thanjavur",
    "location": "Nachiar Koil",
    "god": "Srinivasan",
    "goddess": "Vanjulavalli",
    "history": "இங்கு தாயாருக்கே முதல் மரியாதை. இத்தலத்தின் கல் கருடன் வாகனம் மிகவும் புகழ்பெற்றது.",
    "travel": "கும்பகோணத்திலிருந்து 10 கி.மீ. திருவாரூர் செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD015",
    "name_ta": "திருச்சேறை",
    "name_en": "Thirucherai Sarathan",
    "district": "Thanjavur",
    "location": "Thirucherai",
    "god": "Saranatha Perumal",
    "goddess": "Saranayaki",
    "history": "காவேரி தாய்க்கு இறைவன் காட்சி தந்த இடம். இங்கு 5 தாயார்கள் சன்னதி உள்ளது சிறப்பு.",
    "travel": "கும்பகோணத்திலிருந்து 15 கி.மீ. திருவாரூர் செல்லும் சாலையில் உள்ளது."
  },
  {
    "id": "DD016",
    "name_ta": "திருக்கண்ணமங்கை",
    "name_en": "Thirukannamangai",
    "district": "Tiruvarur",
    "location": "Thirukannamangai",
    "god": "Bhakthavatsalan",
    "goddess": "Abishekavalli",
    "history": "இறைவன் தேனீக்களாக வந்து வழிபடும் தலம். இங்குள்ள தேன்கூடு இன்றும் பாதுகாக்கப்படுகிறது.",
    "travel": "திருவாரூரிலிருந்து 6 கி.மீ தொலைவில் கும்பகோணம் செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD017",
    "name_ta": "திருக்கண்ணபுரம்",
    "name_en": "Thirukannapuram",
    "district": "Nagapattinam",
    "location": "Thirukannapuram",
    "god": "Sowrirajan",
    "goddess": "Kannapura Nayaki",
    "history": "இங்கு இறைவன் சௌரி (முடி) உடன் காட்சி தருகிறார். முனையதரன் பொங்கல் இத்தலத்தின் சிறப்பு நிவேதனம்.",
    "travel": "நன்னிலத்திலிருந்து 10 கி.மீ. நாகப்பட்டினம் - திருவாரூர் சாலையில் உள்ளது."
  },
  {
    "id": "DD018",
    "name_ta": "திருக்கண்ணங்குடி",
    "name_en": "Thirukannangudi",
    "district": "Nagapattinam",
    "location": "Thirukannangudi",
    "god": "Loganatha Perumal",
    "goddess": "Loganayaki",
    "history": "வசிஷ்ட முனிவர் வெண்ணெயால் செய்த கிருஷ்ண விக்கிரகம் உருகாமல் இருந்த தலம்.",
    "travel": "சிக்கலிலிருந்து 2 கி.மீ. நாகப்பட்டினம் - திருவாரூர் சாலையில் உள்ளது."
  },
  {
    "id": "DD019",
    "name_ta": "திருநாகை",
    "name_en": "Thirunagai (Nagapattinam)",
    "district": "Nagapattinam",
    "location": "Nagapattinam",
    "god": "Soundaryarajan",
    "goddess": "Soundaryavalli",
    "history": "நாகராஜன் வழிபட்டு முக்தி அடைந்த தலம். இங்குள்ள துருவ நட்சத்திர விக்கிரகம் மிக அழகானது.",
    "travel": "நாகப்பட்டினம் நகரின் மையப்பகுதியில் அமைந்துள்ளது."
  },
  {
    "id": "DD020",
    "name_ta": "தஞ்சை மாமணிக் கோவில்",
    "name_en": "Thanjai Mamani Kovil",
    "district": "Thanjavur",
    "location": "Thanjavur",
    "god": "Neelamega Perumal",
    "goddess": "Shengamlavalli",
    "history": "தஞ்சகன், தண்டகன், கஜமுகன் ஆகிய அரக்கர்களை இறைவன் அழித்த தலம். மூன்று கோயில்கள் சேர்ந்தது இத்தலம்.",
    "travel": "தஞ்சாவூரிலிருந்து 5 கி.மீ. வெண்ணாற்றங்கரையில் திருவையாறு செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD021",
    "name_ta": "நந்திபுர விண்ணகரம்",
    "name_en": "Nandipuravinnagaram",
    "district": "Thanjavur",
    "location": "Nathan Kovil",
    "god": "Jagannathan",
    "goddess": "Shenbagavalli",
    "history": "நந்தி தேவர் சாபம் நீங்கப் பெற்று இறைவனை வழிபட்ட தலம்.",
    "travel": "கும்பகோணத்திலிருந்து 5 கி.மீ. பட்டீஸ்வரத்திற்கு அருகில் உள்ளது."
  },
  {
    "id": "DD022",
    "name_ta": "திருவெள்ளியங்குடி",
    "name_en": "Thiruvelliyangudi",
    "district": "Thanjavur",
    "location": "Thiruvelliyangudi",
    "god": "Kolavilli Raman",
    "goddess": "Maragathavalli",
    "history": "சுக்கிராச்சாரியார் (வெள்ளி) இத்தல இறைவனை வழிபட்டு கண்பார்வை பெற்ற தலம்.",
    "travel": "கும்பகோணத்திலிருந்து 18 கி.மீ. அணைக்கரை செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD023",
    "name_ta": "திருவழுந்தூர்",
    "name_en": "Thiruvazhundur",
    "district": "Mayiladuthurai",
    "location": "Therazhundur",
    "god": "Devaadi Raja",
    "goddess": "Senkamalavalli",
    "history": "கம்பர் அவதரித்த தலம். இங்கு மூலவர் தேவாதிராஜன் பிரம்மாண்டமான கோலத்தில் காட்சி தருகிறார்.",
    "travel": "மயிலாடுதுறையிலிருந்து 12 கி.மீ. குத்தாலம் அருகில் உள்ளது."
  },
  {
    "id": "DD024",
    "name_ta": "திருக்கோவிலூர்",
    "name_en": "Thirukkovilur",
    "district": "Kallakurichi",
    "location": "Tirukkovilur",
    "god": "Thiruvikraman",
    "goddess": "Poongothai",
    "history": "முதலாவழ்வார்கள் மூவரும் ஒன்று சந்தித்த தலம். இங்கு விஷ்ணு உலகளந்த பெருமாளாகக் காட்சி தருகிறார்.",
    "travel": "விழுப்புரத்திலிருந்து 40 கி.மீ. திருவண்ணாமலை செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD025",
    "name_ta": "தலைச்சங்கநாள் மதியம்",
    "name_en": "Thalaichanganaanmathiyam",
    "district": "Mayiladuthurai",
    "location": "Thalaichangadu",
    "god": "Naan Madhiya Perumal",
    "goddess": "Senkamalavalli",
    "history": "சந்திரனின் சாபம் நீங்கிய தலம். இங்குள்ள பெருமாள் சந்திரனைத் தன் தலையில் சூடியிருக்கிறார்.",
    "travel": "மயிலாடுதுறையிலிருந்து 20 கி.மீ. சீர்காழி செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD026",
    "name_ta": "திருஇந்தளூர்",
    "name_en": "Thiru Indhaloor",
    "district": "Mayiladuthurai",
    "location": "Mayiladuthurai",
    "god": "Parimala Ranganatha",
    "goddess": "Parimala Ranganayaki",
    "history": "சந்திரன் (இந்து) சாபம் நீங்கிய தலம். இங்கு இறைவன் நறுமணம் வீசும் மலர்களால் ஆன பள்ளியில் சயனிப்பதால் 'பரிமல ரங்கநாதர்' எனப்படுகிறார்.",
    "travel": "மயிலாடுதுறை நகருக்குள்ளேயே அமைந்துள்ளது. பேருந்து மற்றும் இரயில் வசதி உள்ளது."
  },
  {
    "id": "DD027",
    "name_ta": "காழிச்சீராம விண்ணகர்",
    "name_en": "Kaazhicheerama Vinnagaram",
    "district": "Mayiladuthurai",
    "location": "Sirkazhi",
    "god": "Thadalar (Trivikraman)",
    "goddess": "Lokanaayaki",
    "history": "இறைவன் உலகளந்த பெருமாளாக (திரிவிக்ரமன்) ஒரு காலைத் தூக்கியபடி காட்சி தருகிறார். சீர்காழி நகரில் அமைந்துள்ளது.",
    "travel": "சீர்காழி பேருந்து நிலையத்திலிருந்து 2 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD028",
    "name_ta": "திருவாலி-திருநகரி",
    "name_en": "Thiruvali-Thirunagari",
    "district": "Mayiladuthurai",
    "location": "Thiruvali",
    "god": "Lakshmi Narasimhar / Vedharaja",
    "goddess": "Amruthavalli",
    "history": "திருமங்கையாழ்வார் இறைவனை வழிமறித்த தலம். இவை இரண்டு தனித்தனி ஊர்கள் என்றாலும் ஒரு திவ்ய தேசமாகக் கருதப்படுகிறது.",
    "travel": "சீர்காழியிலிருந்து 10 கி.மீ. தொலைவில் உள்ளது. திருநாங்கூர் பகுதிக்கு அருகாமையில் உள்ளது."
  },
  {
    "id": "DD029",
    "name_ta": "அரிமேய விண்ணகரம்",
    "name_en": "Arimeya Vinnagaram",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Kuda Maadu Koothan",
    "goddess": "Amruthagadavalli",
    "history": "திருநாங்கூர் பதினொரு திவ்ய தேசங்களில் ஒன்று. இறைவன் சதுர்புஜங்களுடன் நின்ற கோலத்தில் காட்சி தருகிறார்.",
    "travel": "சீர்காழியிலிருந்து 8 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD030",
    "name_ta": "திருவண் புருஷோத்தமம்",
    "name_en": "Thiruvan Purushothamam",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Purushothaman",
    "goddess": "Purushothama Naayaki",
    "history": "புருஷோத்தம முனிவருக்கு இறைவன் காட்சி தந்து உபதேசம் செய்த தலம்.",
    "travel": "சீர்காழியிலிருந்து 8 கி.மீ. திருநாங்கூர் கிராமத்தில் உள்ளது."
  },
  {
    "id": "DD031",
    "name_ta": "செம்பொன் செங்கோயில்",
    "name_en": "Sempon Seyarkovil",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Perarulalan",
    "goddess": "Allimamalar Naayaki",
    "history": "ராமபிரான் ராவண வதம் செய்த பின் ஏற்பட்ட பிரம்மஹத்தி தோஷம் நீங்க இங்கு வந்து வழிபட்டதாக வரலாறு.",
    "travel": "திருநாங்கூர் பகுதியில் மற்ற திவ்ய தேசங்களுக்கு அருகிலேயே உள்ளது."
  },
  {
    "id": "DD032",
    "name_ta": "மணி மாடக் கோவில்",
    "name_en": "Thiru Manimaada Kovil",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Narayana Perumal",
    "goddess": "Pundareegavalli",
    "history": "திருநாங்கூர் 11 கருட சேவை இங்கிருந்தே தொடங்கும். நந்தா விளக்கு எரிந்துகொண்டே இருக்கும் சிறப்புடையது.",
    "travel": "சீர்காழி - திருவெண்காடு பாதையில் திருநாங்கூரில் உள்ளது."
  },
  {
    "id": "DD033",
    "name_ta": "வைகுண்ட விண்ணகரம்",
    "name_en": "Thiru Vaikunta Vinnagaram",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Vaikuntanathan",
    "goddess": "Vaikundavalli",
    "history": "வைகுண்டத்தில் இருப்பது போலவே இறைவன் இங்கும் வீற்றிருக்கும் கோலத்தில் காட்சி தருகிறார்.",
    "travel": "திருநாங்கூர் திவ்ய தேச வழித்தடத்தில் அமைந்துள்ளது."
  },
  {
    "id": "DD034",
    "name_ta": "திருத்தேவன்பத்தொகை",
    "name_en": "Thiru Thevanpaththogai",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Deivanayaga Perumal",
    "goddess": "Kadalmagal Naayaki",
    "history": "தேவர்கள் அனைவரும் ஒன்றாகக் குழுமி இறைவனை வழிபட்டதால் 'தேவன்பத்தொகை' என அழைக்கப்படுகிறது.",
    "travel": "சீர்காழியிலிருந்து 10 கி.மீ. திருநாங்கூர் அருகே உள்ளது."
  },
  {
    "id": "DD035",
    "name_ta": "திருத்தெற்றியம்பலம்",
    "name_en": "Thiruthetriyambalam",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Senkanmaal Ranganathar",
    "goddess": "Senkamalavalli",
    "history": "இங்குள்ள இறைவன் செங்கண்மால் (சிவந்த கண்களை உடையவன்) என்று அழைக்கப்படுகிறார். சயன கோலம்.",
    "travel": "திருநாங்கூர் வழித்தடத்தில் மற்ற கோயில்களுக்கு மிக அருகில் உள்ளது."
  },
  {
    "id": "DD036",
    "name_ta": "திருமணிக்கூடம்",
    "name_en": "Thirumanikkoodam",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Varadharaja Perumal",
    "goddess": "Thirumamagal",
    "history": "சந்திர பகவான் சாபம் நீங்க இங்குள்ள புஷ்கரிணியில் நீராடி இறைவனை வழிபட்டதாகக் கூறப்படுகிறது.",
    "travel": "திருநாங்கூர் திவ்ய தேசங்களின் ஒரு பகுதியாகும்."
  },
  {
    "id": "DD037",
    "name_ta": "திருகாவளம்பாடி",
    "name_en": "Thiru Kavalampaadi",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Gopala Krishna",
    "goddess": "Madavaral Mangai",
    "history": "துவாரகையில் உள்ள கிருஷ்ணனைப் போலவே இங்கும் கிருஷ்ணர் காட்சி தருகிறார்.",
    "travel": "திருநாங்கூர் பகுதியில் அமைந்துள்ளது."
  },
  {
    "id": "DD038",
    "name_ta": "திருவெள்ளக்குளம்",
    "name_en": "Thiru Vellakulam (Annan Kovil)",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Srinivasan",
    "goddess": "Padmavathi",
    "history": "திருப்பதி சீனிவாசனுக்கு இது அண்ணன் கோயில் என்று கருதப்படுகிறது. திருமங்கையாழ்வார் குமுதவல்லி நாச்சியாரை மணந்த இடம்.",
    "travel": "சீர்காழியிலிருந்து 10 கி.மீ. பூம்புகார் செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD039",
    "name_ta": "திருபார்த்தன்பள்ளி",
    "name_en": "Thiru Paarthanpalli",
    "district": "Mayiladuthurai",
    "location": "Thirunangur",
    "god": "Thamaraikkannan",
    "goddess": "Thamarainaayaki",
    "history": "அர்ஜுனன் (பார்த்தன்) தாகம் தீர்க்க இங்குள்ள கிணறு உருவானதாக வரலாறு. கிருஷ்ணர் அர்ஜுனனுக்குக் காட்சி தந்த தலம்.",
    "travel": "திருநாங்கூரிலிருந்து 2 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD040",
    "name_ta": "திருச்சித்திரகூடம்",
    "name_en": "Thiruchitrakootam (Chidambaram)",
    "district": "Cuddalore",
    "location": "Chidambaram",
    "god": "Govindaraja Perumal",
    "goddess": "Pundareegavalli",
    "history": "தில்லை நடராஜர் கோயில் வளாகத்திலேயே கோவிந்தராஜப் பெருமாள் சன்னதி அமைந்துள்ளது. சைவ, வைணவ ஒற்றுமைக்குச் சான்று.",
    "travel": "சிதம்பரம் நகரின் மையத்தில் உள்ள நடராஜர் கோயிலுக்குள் உள்ளது."
  },
  {
    "id": "DD041",
    "name_ta": "திருவாஹிந்திரபுரம்",
    "name_en": "Thiruvaheendrapuram",
    "district": "Cuddalore",
    "location": "Cuddalore",
    "god": "Devanathan Perumal",
    "goddess": "Hemabhujavalli",
    "history": "வேதாந்த தேசிகர் வழிபட்ட தலம். இங்குள்ள ஔஷதகிரி மலையில் ஹயக்ரீவர் சன்னதி மிகவும் விசேஷமானது.",
    "travel": "கடலூரிலிருந்து 5 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD042",
    "name_ta": "திருக்கோவிலூர்",
    "name_en": "Thirukkovilur",
    "district": "Kallakurichi",
    "location": "Tirukkovilur",
    "god": "Ulagalantha Perumal (Thiruvikraman)",
    "goddess": "Poongothai",
    "history": "முதலாவழ்வார்கள் மூவரும் ஒரு சிறிய இடைழியில் இறைவனைத் தரிசித்த இடம். நாலாயிர திவ்ய பிரபந்தத்தின் முதல் பாடல்கள் இங்குதான் பாடப்பட்டன.",
    "travel": "விழுப்புரத்திலிருந்து 40 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD043",
    "name_ta": "திருக்கச்சி",
    "name_en": "Kanchipuram Varadharajar",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Varadharajar",
    "goddess": "Perundevi",
    "history": "பேரருளாளன் வசிக்கும் தலம். அத்தி வரதர் மிகவும் பிரசித்தி பெற்றவர். தங்க மற்றும் வெள்ளிப் பல்லிகளைத் தொடுவது விசேஷம்.",
    "travel": "காஞ்சிபுரம் சின்ன காஞ்சிபுரம் பகுதியில் அமைந்துள்ளது."
  },
  {
    "id": "DD044",
    "name_ta": "திருவெக்கா",
    "name_en": "Thiru Vekka",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Yathothakaari",
    "goddess": "Komalavalli",
    "history": "சொன்ன வண்ணம் செய்த பெருமாள். திருமழிசையாழ்வாரின் வேண்டுகோளுக்கு இணங்க இறைவன் பாயைச் சுருட்டிக் கொண்டு கிளம்பிய தலம்.",
    "travel": "காஞ்சிபுரம் வரதராஜர் கோயிலுக்கு அருகிலேயே உள்ளது."
  },
  {
    "id": "DD045",
    "name_ta": "திரு அஷ்டபுயகரம்",
    "name_en": "Thiru Ashtabuyakaram",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Aadhikesava Perumal",
    "goddess": "Padmasani",
    "history": "இறைவன் எட்டு கைகளுடன் ஆயுதங்கள் ஏந்தி ஆதிசேஷன் மேல் அமர்ந்த கோலத்தில் காட்சி தருகிறார்.",
    "travel": "காஞ்சிபுரம் வரதராஜர் கோயிலிலிருந்து 2 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD046",
    "name_ta": "திருஊரகம்",
    "name_en": "Thiru Ooragam",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Ulagalantha Perumal",
    "goddess": "Amruthavalli",
    "history": "பிரம்மாண்டமான 35 அடி உயர உலகளந்த பெருமாள் சிலை இங்குள்ளது. ஒரே கோயிலுக்குள் நான்கு திவ்ய தேசங்கள் உள்ளன.",
    "travel": "காஞ்சிபுரம் பேருந்து நிலையத்திற்கு மிக அருகில் உள்ளது."
  },
  {
    "id": "DD047",
    "name_ta": "திருநீரகம்",
    "name_en": "Thiru Neeragam",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Jagadeeshwarar",
    "goddess": "Nilamangai",
    "history": "உலகளந்த பெருமாள் கோயில் பிரகாரத்திலேயே இந்த திவ்ய தேச சன்னதி உள்ளது.",
    "travel": "காஞ்சிபுரம் உலகளந்த பெருமாள் கோயிலுக்குள் உள்ளது."
  },
  {
    "id": "DD048",
    "name_ta": "திருகாரகம்",
    "name_en": "Thiru Kaaragam",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Karunakara Perumal",
    "goddess": "Padmamani",
    "history": "காரக முனிவருக்கு இறைவன் கருணை காட்டி காட்சி கொடுத்த தலம்.",
    "travel": "காஞ்சிபுரம் உலகளந்த பெருமாள் கோயிலுக்குள் உள்ளது."
  },
  {
    "id": "DD049",
    "name_ta": "திருக்கார்வானம்",
    "name_en": "Thirukkaar Vaanam",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Thirukkaar Vaanar",
    "goddess": "Kamalavalli",
    "history": "மேகத்தைப் போன்ற கருணை உடையவன் என்பதால் 'கார்வானர்' என்று அழைக்கப்படுகிறார்.",
    "travel": "காஞ்சிபுரம் உலகளந்த பெருமாள் கோயிலுக்குள் உள்ளது."
  },
  {
    "id": "DD050",
    "name_ta": "திருபரமேஸ்வர விண்ணகரம்",
    "name_en": "Thiru Parameswara Vinnagaram",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Vaikunda Perumal",
    "goddess": "Vaikundavalli",
    "history": "பல்லவ மன்னன் பரமேஸ்வர வர்மனால் கட்டப்பட்டது. இங்குள்ள சிற்பங்கள் மிகவும் நுணுக்கமானவை.",
    "travel": "காஞ்சிபுரம் இரயில் நிலையத்திற்கு அருகிலேயே உள்ளது."
  },
  {
    "id": "DD051",
    "name_ta": "திருப்பாடகம்",
    "name_en": "Thiru Paadagam (Pandava Thoothar)",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Pandava Thoothar",
    "goddess": "Rukmani Piratti",
    "history": "பாண்டவர்களுக்காகத் தூது சென்ற கண்ணன், துரியோதனன் சபையில் காட்டிய விஸ்வரூபக் கோலத்தில் 25 அடி உயரத்தில் அமர்ந்த நிலையில் காட்சி தருகிறார்.",
    "travel": "காஞ்சிபுரம் ஏகாம்பரநாதர் கோயிலுக்கு அருகிலேயே அமைந்துள்ளது."
  },
  {
    "id": "DD052",
    "name_ta": "திருநிலாத்திங்கள் துண்டம்",
    "name_en": "Thiru Nilathingal Thundam",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Nilathingal Thundathan",
    "goddess": "Nilaathingal Naayaki",
    "history": "ஏகாம்பரநாதர் (சிவன்) கோயில் பிரகாரத்தின் உள்ளேயே அமைந்துள்ள விஷ்ணு சன்னதி. பார்வதி தேவி தவம் செய்த போது சிவபெருமானின் நெற்றிக்கண் வெப்பத்தைத் தணிக்க திருமால் நிலவின் ஒளியைத் தந்த தலம்.",
    "travel": "காஞ்சிபுரம் ஏகாம்பரநாதர் கோயிலின் முதல் பிரகாரத்தில் உள்ளது."
  },
  {
    "id": "DD053",
    "name_ta": "திருவேளுக்கை",
    "name_en": "Thiru Velukkai",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Azhagiya Singar (Narasimhar)",
    "goddess": "Velukkai Valli",
    "history": "நரசிம்மர் அசுரர்களை விரட்டிவிட்டு 'வேளுக்கை' (விருப்பத்துடன் தங்குதல்) கொண்ட தலம். யோக நரசிம்மராகக் காட்சி தருகிறார்.",
    "travel": "காஞ்சிபுரம் வரதராஜர் கோயிலிலிருந்து 2 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD054",
    "name_ta": "திருத்தண்கா",
    "name_en": "Thiru Thankaa (Deepa Prakasar)",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Deepa Prakasar",
    "goddess": "Maragathavalli",
    "history": "வேதாந்த தேசிகர் அவதரித்த தலம். பிரம்மா செய்த யாகத்தை அசுரர்கள் இருட்டாக்கியபோது, இறைவன் ஒளியாகத் தோன்றி இருளை நீக்கியதால் 'தீபப் பிரகாசர்' எனப்படுகிறார்.",
    "travel": "காஞ்சிபுரம் விளக்கொளிப் பெருமாள் கோயில் என்று மக்களால் அழைக்கப்படுகிறது."
  },
  {
    "id": "DD055",
    "name_ta": "திருப்புத்குழி",
    "name_en": "Thiru Putkuzhi",
    "district": "Kanchipuram",
    "location": "Baluchetti Chattram",
    "god": "Vijayaraghava Perumal",
    "goddess": "Maragathavalli",
    "history": "ராமபிரான் ஜடாயுவுக்கு முக்தி அளித்த தலம். ஜடாயுவின் சிறகால் ஏற்பட்ட குழியில் ராமன் இறுதிச் சடங்கு செய்ததால் 'புத்குழி' (புள் - பறவை) எனப் பெயர் பெற்றது.",
    "travel": "காஞ்சிபுரம் - வேலூர் நெடுஞ்சாலையில் காஞ்சியிலிருந்து 12 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD056",
    "name_ta": "திருப்பவள வண்ணம்",
    "name_en": "Thiru Pavala Vannam",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Pavala Vannar",
    "goddess": "Pavala Valli",
    "history": "இறைவன் பவளம் போன்ற சிவந்த நிறத்தில் காட்சி தருகிறார். இங்கு பச்சை வண்ணர் மற்றும் பவள வண்ணர் என இரு கோயில்கள் உள்ளன.",
    "travel": "காஞ்சிபுரம் பேருந்து நிலையத்திற்கு மிக அருகில் உள்ளது."
  },
  {
    "id": "DD057",
    "name_ta": "திருப்பாடகம் (மற்றொரு சன்னதி/தொடர்ச்சி)",
    "name_en": "Thiru Paramechura Vinnagaram",
    "district": "Kanchipuram",
    "location": "Kanchipuram",
    "god": "Vaikunta Perumal",
    "goddess": "Vaikundavalli",
    "history": "பல்லவக் கட்டிடக்கலைக்குச் சான்றான கோயில். இங்கு இறைவன் அமர்ந்த, நின்ற மற்றும் கிடந்த கோலங்களில் மூன்று நிலைகளில் காட்சி தருகிறார்.",
    "travel": "காஞ்சிபுரம் இரயில் நிலையத்திற்கு மிக அருகில் உள்ளது."
  },
  {
    "id": "DD058",
    "name_ta": "திருநீர்மலை",
    "name_en": "Thiru Neermalai",
    "district": "Chengalpattu",
    "location": "Pallavaram",
    "god": "Neervanna Perumal",
    "goddess": "Animagarmangai",
    "history": "மலை மேல் ஒரு கோயிலும் மலைக் கீழே ஒரு கோயிலும் உள்ளது. திருமங்கையாழ்வார் வந்தபோது மலையைச் சுற்றி நீர் சூழ்ந்திருந்ததால் இது நீர்மலை எனப்பட்டது.",
    "travel": "சென்னையில் பல்லாவரத்திலிருந்து 4 கி.மீ. தொலைவில் உள்ளது. சுமார் 200 படிகள் ஏற வேண்டும்."
  },
  {
    "id": "DD059",
    "name_ta": "திருவிடந்தை",
    "name_en": "Thiru Vidandhai",
    "district": "Chengalpattu",
    "location": "ECR, Chennai",
    "god": "Nithya Kalyana Perumal",
    "goddess": "Komalavalli",
    "history": "ராகு-கேது தோஷங்கள் நீங்கும் தலம். இறைவன் தினமும் ஒரு கல்யாணம் செய்து கொள்வதால் 'நித்ய கல்யாண பெருமாள்' எனப்படுகிறார். திருமணத் தடை நீங்கப் புகழ்பெற்ற தலம்.",
    "travel": "சென்னை கிழக்கு கடற்கரை சாலையில் (ECR) கோவளத்திற்கு அருகில் உள்ளது."
  },
  {
    "id": "DD060",
    "name_ta": "திருக்கடல்மல்லை",
    "name_en": "Thirukadalmallai (Mahabalipuram)",
    "district": "Chengalpattu",
    "location": "Mahabalipuram",
    "god": "Sthala Sayana Perumal",
    "goddess": "Nilamangai",
    "history": "பூதத்தாழ்வார் அவதரித்த தலம். அலைகள் மோதும் கடற்கரை ஓரம் இறைவன் தரையில் பள்ளி கொண்ட கோலத்தில் (Sthala Sayanam) காட்சி தருகிறார்.",
    "travel": "மகாபலிபுரம் நகரின் மையப்பகுதியில் பேருந்து நிலையத்திற்கு அருகில் உள்ளது."
  },
  {
    "id": "DD061",
    "name_ta": "திருவல்லிக்கேணி",
    "name_en": "Thiruvallikeni (Triplicane)",
    "district": "Chennai",
    "location": "Triplicane",
    "god": "Parthasarathy Perumal",
    "goddess": "Vedhavalli",
    "history": "கண்ணன் அர்ஜுனனுக்குத் தேரோட்டிய கோலத்தில் (பார்த்தசாரதி) மீசையுடன் காட்சி தருகிறார். ஒரே கோயிலில் ஐந்து அவதாரங்களுக்குச் சன்னதிகள் உள்ளன.",
    "travel": "சென்னை நகரின் மையப்பகுதியில் உள்ளது. இரயில் மற்றும் பேருந்து வசதி மிக அதிகம்."
  },
  {
    "id": "DD062",
    "name_ta": "திருநீரகம் (சென்னை - திருநின்றவூர்)",
    "name_en": "Thiru Ninravur",
    "district": "Tiruvallur",
    "location": "Thiruninravur",
    "god": "Bhakthavatsala Perumal",
    "goddess": "Sudhavalli (Ennai Petra Thaayar)",
    "history": "திருமங்கையாழ்வார் பாடாமல் சென்றபோது, தாயார் வேண்டிக் கொண்டதற்கிணங்க இறைவன் ஆழ்வாரைத் தேடிச் சென்று பாடப் பெற்ற தலம்.",
    "travel": "சென்னை - அரக்கோணம் இரயில் பாதையில் திருநின்றவூர் இரயில் நிலையத்திலிருந்து 1 கி.மீ."
  },
  {
    "id": "DD063",
    "name_ta": "திருஎவ்வுள்",
    "name_en": "Thiru Evvul (Thiruvallur)",
    "district": "Tiruvallur",
    "location": "Thiruvallur",
    "god": "Veeraraghava Perumal",
    "goddess": "Kanakavalli",
    "history": "சாலிஹோத்ர முனிவரின் பசி தீர்க்க இறைவன் வந்த தலம். இங்குள்ள தீர்த்தத்தில் நீராடினால் தீராத நோய்கள் மற்றும் உடல் உபாதைகள் நீங்கும் என்பது நம்பிக்கை.",
    "travel": "திருவள்ளூர் நகரின் மையத்தில் உள்ளது. சென்னையில் இருந்து பேருந்து மற்றும் புறநகர் இரயில் வசதி உள்ளது."
  },
  {
    "id": "DD064",
    "name_ta": "திருக்கடிகை",
    "name_en": "Thirukkadigai (Sholingur)",
    "district": "Ranipet",
    "location": "Sholingur",
    "god": "Yoga Narasimhar",
    "goddess": "Amruthavalli",
    "history": "ஒரு 'கடிகை' நேரம் (24 நிமிடங்கள்) இங்கு தங்கினால் முக்தி கிடைக்கும் என்பது ஐதீகம். மலையில் ஆஞ்சநேயரும் நரசிம்மரும் யோக நிலையில் உள்ளனர்.",
    "travel": "அரக்கோணத்திலிருந்து 25 கி.மீ. 1305 படிகள் ஏற வேண்டும். டோலி வசதி உண்டு. குரங்குகள் ஜாக்கிரதை."
  },
  {
    "id": "DD065",
    "name_ta": "திருவனந்தபுரம்",
    "name_en": "Thiruvananthapuram Padmanabhaswamy",
    "district": "Thiruvananthapuram",
    "location": "Kerala",
    "god": "Padmanabhaswamy",
    "goddess": "Hari Lakshmi",
    "history": "பாம்பணையில் துயில் கொள்ளும் பிரம்மாண்டமான இறைவன். மூன்று வாசல் வழியாகத் தரிசனம். உலகிலேயே அதிக நிதியைக் கொண்ட கோயில்.",
    "travel": "கேரள மாநிலத் தலைநகரில் உள்ளது. வேட்டி மற்றும் சேலை போன்ற பாரம்பரிய உடைகள் மட்டுமே அனுமதி."
  },
  {
    "id": "DD066",
    "name_ta": "திருவண்பரிசாரம்",
    "name_en": "Thiruvanparisaram",
    "district": "Kanyakumari",
    "location": "Nagercoil",
    "god": "Thiruvazhmarban",
    "goddess": "Kamalavalli",
    "history": "நம்மாழ்வாரின் தாயார் பிறந்த தலம். திருமாலுடைய மார்பில் மகாலட்சுமி குடியிருப்பதால் 'திருவாழ்மார்பன்' எனப்படுகிறார்.",
    "travel": "நாகர்கோவிலிலிருந்து 4 கி.மீ. திருப்பதிசாரம் என்று அழைக்கப்படுகிறது."
  },
  {
    "id": "DD067",
    "name_ta": "திருவாட்டாறு",
    "name_en": "Thiru Vattaaru",
    "district": "Kanyakumari",
    "location": "Marthandam",
    "god": "Adikesava Perumal",
    "goddess": "Maragathavalli",
    "history": "ஆற்றுக்கு நடுவே அமைந்த தலம். அனந்தசயனக் கோலம். இக்கோயிலின் அமைப்பு ஸ்ரீரங்கம் கோயிலை ஒத்தது.",
    "travel": "நாகர்கோவிலிலிருந்து 30 கி.மீ. மார்த்தாண்டத்திற்கு அருகில் உள்ளது."
  },
  {
    "id": "DD068",
    "name_ta": "திருவனந்தபுரம் (தொடர்ச்சி - மலையாள நாடு)",
    "name_en": "Thiruvithuvakkodu",
    "district": "Palakkad",
    "location": "Kerala",
    "god": "Uyyavantha Perumal",
    "goddess": "Vithuvakkodu Valli",
    "history": "பாண்டவர்கள் ஐவரும் தனித்தனியே இங்கு வந்து இறைவனை வழிபட்டுள்ளனர். பாரதப்புழா ஆற்றின் கரையில் உள்ளது.",
    "travel": "பாலக்காடு மாவட்டத்தில் பட்டாம்பிக்கு அருகில் உள்ளது."
  },
  {
    "id": "DD069",
    "name_ta": "திருக்காட்கரை",
    "name_en": "Thiru Kaatkarai",
    "district": "Ernakulam",
    "location": "Kerala",
    "god": "Katkarayappan (Vamana)",
    "goddess": "Perunchelva Naayaki",
    "history": "மாவலிச் சக்கரவர்த்திக்கு வாமனனாக இறைவன் காட்சி தந்த தலம். ஓணம் பண்டிகையின் பிறப்பிடமாகக் கருதப்படுகிறது.",
    "travel": "எர்ணாகுளம் மாவட்டம் ஆலுவாவிலிருந்து 10 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD070",
    "name_ta": "திருமூழிக்களம்",
    "name_en": "Thiru Moozhikkalam",
    "district": "Ernakulam",
    "location": "Kerala",
    "god": "Lakshmana Perumal",
    "goddess": "Madhuraveni Naayaki",
    "history": "இலட்சுமணனுக்காக அர்ப்பணிக்கப்பட்ட தலம். இறைவன் லட்சுமணனாகக் கருதப்படுகிறார். வேதாந்த ரகசியங்கள் பேசப்பட்ட இடம்.",
    "travel": "ஆலுவாவிலிருந்து 15 கி.மீ. தொலைவில் அமைந்துள்ளது."
  },
  {
    "id": "DD071",
    "name_ta": "திருப்புலியூர்",
    "name_en": "Thiru Puliyur",
    "district": "Alappuzha",
    "location": "Kerala",
    "god": "Mayapiran",
    "goddess": "Porkodi Naayaki",
    "history": "பீமன் வழிபட்ட தலம். இங்குள்ள கதாயுதம் பீமனால் வழங்கப்பட்டது எனப் படுகிறது.",
    "travel": "செங்கனூரிலிருந்து 6 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD072",
    "name_ta": "திருச்செங்குன்றூர்",
    "name_en": "Thiru Chengannur",
    "district": "Alappuzha",
    "location": "Kerala",
    "god": "Imayavarappan",
    "goddess": "Sengamala Valli",
    "history": "தர்மர் (யுதிஷ்டிரன்) வழிபட்ட தலம். மகாபாரதப் போருக்குப் பின் அவர் இங்கு தவம் செய்ததாக வரலாறு.",
    "travel": "செங்கனூர் நகரின் மையப்பகுதியிலேயே உள்ளது."
  },
  {
    "id": "DD073",
    "name_ta": "திருவண்வண்டூர்",
    "name_en": "Thiru Vanvandur",
    "district": "Alappuzha",
    "location": "Kerala",
    "god": "Paambanaiappan",
    "goddess": "Kamalavalli",
    "history": "நகுலன் வழிபட்ட தலம். பம்பை ஆற்றின் கரையில் அமைந்துள்ளது. நாகப் பாம்பின் மேல் இறைவன் அமர்ந்துள்ளார்.",
    "travel": "செங்கனூரிலிருந்து 8 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD074",
    "name_ta": "திருவல்லவாழ்",
    "name_en": "Thiru Vallavazh",
    "district": "Pathanamthitta",
    "location": "Kerala",
    "god": "Thiruvallabhappan",
    "goddess": "Selvathirukozhunthu",
    "history": "பெண்களுக்குப் புனிதமான தலம். இங்குள்ள இறைவனுக்கு தினமும் கதகளி ஆடல் வழிபாடு நடைபெறுகிறது.",
    "travel": "திருவல்லா இரயில் நிலையத்திலிருந்து 4 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD075",
    "name_ta": "திருக்கடித்தானம்",
    "name_en": "Thiru Kadithaanam",
    "district": "Kottayam",
    "location": "Kerala",
    "god": "Amrutha Narayanan",
    "goddess": "Karpagavalli",
    "history": "சகாதேவன் வழிபட்ட தலம். இங்கு இறைவன் நரசிம்மரின் அம்சமாக வழிபடப்படுகிறார்.",
    "travel": "செங்கனூர் மற்றும் திருவல்லாவிற்கு அருகில் உள்ளது."
  },
  {
    "id": "DD076",
    "name_ta": "திருப்பரிசாரம் (திருவண்பரிசாரம்)",
    "name_en": "Thiruvanparisaram",
    "district": "Kanyakumari",
    "location": "Nagercoil",
    "god": "Thiruvazhmarban",
    "goddess": "Kamalavalli",
    "history": "நம்மாழ்வாரின் தாயார் உடையநங்கை அவதரித்த தலம். இறைவன் தன் மார்பில் மகாலட்சுமியைத் தாங்கியிருப்பதால் இப்பெயர் பெற்றது.",
    "travel": "நாகர்கோவிலிலிருந்து 4 கி.மீ. தொலைவில் உள்ளது. இது 'திருப்பதிசாரம்' என்றும் அழைக்கப்படுகிறது."
  },
  {
    "id": "DD077",
    "name_ta": "திருக்காட்கரை",
    "name_en": "Thirukaatkara",
    "district": "Ernakulam",
    "location": "Kerala",
    "god": "Kaatkarayappan",
    "goddess": "Perunchelva Nayaki",
    "history": "வாமன அவதாரத்துடன் தொடர்புடைய தலம். மாவலி சக்கரவர்த்திக்கு இறைவன் காட்சி தந்த இடம். ஓணம் பண்டிகை இங்கிருந்தே தொடங்கியது.",
    "travel": "எர்ணாகுளம் மாவட்டம் இடப்பள்ளிக்கு அருகில் உள்ளது."
  },
  {
    "id": "DD078",
    "name_ta": "திருமூழிக்களம்",
    "name_en": "Thirumoozhikkalam",
    "district": "Ernakulam",
    "location": "Kerala",
    "god": "Sree Lakshmana Perumal",
    "goddess": "Madhuraveni Nayaki",
    "history": "ராமாயணத்தில் லக்ஷ்மணன் வழிபட்ட தலம். 'திருமொழி' (வேதங்கள்) இங்கு சொல்லப்பட்டதால் திருமூழிக்களம் எனப்பட்டது.",
    "travel": "ஆலுவாவிலிருந்து 15 கி.மீ. தொலைவில் அமைந்துள்ளது."
  },
  {
    "id": "DD079",
    "name_ta": "திருக்கோடிட்டித்தானம்",
    "name_en": "Thirukkadithanam",
    "district": "Kottayam",
    "location": "Kerala",
    "god": "Amrutha Narayanan",
    "goddess": "Karpagavalli",
    "history": "சகாதேவனால் புதுப்பிக்கப்பட்ட தலம். இங்குள்ள நரசிம்மர் வடிவம் மிகவும் சக்தி வாய்ந்தது.",
    "travel": "சங்கனாச்சேரியிலிருந்து 3 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD080",
    "name_ta": "திருவாறன்விளை (ஆரன்முளா)",
    "name_en": "Thiruvaaranvilai",
    "district": "Pathanamthitta",
    "location": "Kerala",
    "god": "Parthasarathy",
    "goddess": "Thirumagal",
    "history": "அர்ஜுனன் வழிபட்ட தலம். இங்குள்ள இறைவனுக்கு நிவேதிக்கப்படும் 'ஆரன்முளா கண்ணாடி' உலகப் புகழ் பெற்றது.",
    "travel": "செங்கனூரிலிருந்து 10 கி.மீ. தொலைவில் பம்பை ஆற்றின் கரையில் உள்ளது."
  },
  {
    "id": "DD081",
    "name_ta": "திருப்புலியூர்",
    "name_en": "Thirupuliyur",
    "district": "Alappuzha",
    "location": "Kerala",
    "god": "Mayapiran",
    "goddess": "Porkodi Nayaki",
    "history": "பீமன் வழிபட்ட தலம். பீமனின் கதாயுதம் இங்குள்ள குளத்தில் கண்டெடுக்கப்பட்டதாக ஐதீகம்.",
    "travel": "செங்கனூரிலிருந்து 6 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD082",
    "name_ta": "திருச்செங்குன்றூர்",
    "name_en": "Thiruchenkundrur",
    "district": "Alappuzha",
    "location": "Kerala",
    "god": "Imayavarappan",
    "goddess": "Senkamala Valli",
    "history": "தர்மர் வழிபட்ட தலம். இமயமலைத் தேவர்கள் வந்து வழிபட்டதால் இறைவனுக்கு 'இமையவரப்பன்' என்று பெயர்.",
    "travel": "செங்கனூர் இரயில் நிலையத்திலிருந்து 1 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD083",
    "name_ta": "திருநாவாய்",
    "name_en": "Thirunavaya",
    "district": "Malappuram",
    "location": "Kerala",
    "god": "Nava Mukundan",
    "goddess": "Malarmangai Naachiyar",
    "history": "பாரதப்புழா ஆற்றின் கரையில் உள்ளது. காசிக்கு நிகராகப் பிதுர் தர்ப்பணம் செய்யுமிடம்.",
    "travel": "குற்றிப்புரம் இரயில் நிலையத்திலிருந்து 2 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD084",
    "name_ta": "திருவித்துவக்கோடு",
    "name_en": "Thiruvithuvakkodu",
    "district": "Palakkad",
    "location": "Kerala",
    "god": "Uyyavantha Perumal",
    "goddess": "Vithuvakkodu Valli",
    "history": "குலசேகர ஆழ்வார் 'தருதுயரம் தடாயேல்' என்று பாடிய தலம். பாண்டவர்கள் வழிபட்ட ஐந்து மூர்த்திகள் இங்குள்ளனர்.",
    "travel": "பட்டாம்பி இரயில் நிலையத்திலிருந்து 4 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD085",
    "name_ta": "திருவில்லிபுத்தூர்",
    "name_en": "Srivilliputhur",
    "district": "Virudhunagar",
    "location": "Srivilliputhur",
    "god": "Vatapatrasayi",
    "goddess": "Andal",
    "history": "ஆண்டாள் மற்றும் பெரியாழ்வார் அவதரித்த தலம். திருப்பாவை பிறந்த இடம். தமிழக அரசின் சின்னம் இக்கோயில் கோபுரமே.",
    "travel": "மதுரையிலிருந்து 80 கி.மீ. தொலைவில் உள்ளது. பேருந்து மற்றும் இரயில் வசதி உண்டு."
  },
  {
    "id": "DD086",
    "name_ta": "திருக்கோட்டியூர்",
    "name_en": "Thirukoshtiyur",
    "district": "Sivaganga",
    "location": "Thirukoshtiyur",
    "god": "Soumya Narayana Perumal",
    "goddess": "Thirumamagal",
    "history": "ராமானுஜர் 'ஓம் நமோ நாராயணாய' எனும் மந்திரத்தை உலகிற்கு உரக்கச் சொன்ன கோபுரத்தைக் கொண்ட தலம்.",
    "travel": "திருப்பத்தூரிலிருந்து 8 கி.மீ. சிவகங்கையிலிருந்து 25 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD087",
    "name_ta": "திருமெய்யம்",
    "name_en": "Thirumeyyam",
    "district": "Pudukkottai",
    "location": "Thirumeyyam",
    "god": "Sathya Girinathan",
    "goddess": "Uyya Vandha Naachiyar",
    "history": "மலையைக் குடைந்து அமைக்கப்பட்ட குடைவரை கோயில். மிகப்பெரிய ஆதிசேஷன் மேல் இறைவன் சயனித்திருக்கிறார்.",
    "travel": "புதுக்கோட்டையிலிருந்து 20 கி.மீ. காரைக்குடி செல்லும் பாதையில் உள்ளது."
  },
  {
    "id": "DD088",
    "name_ta": "திருப்புல்லாணி",
    "name_en": "Thiruppullani",
    "district": "Ramanathapuram",
    "location": "Thiruppullani",
    "god": "Adi Jagannathar",
    "goddess": "Padmasani",
    "history": "ராமபிரான் கடலுக்குப் பாலம் கட்டும் முன் தர்பை புல்லின் மேல் சயனித்து வழிபட்ட தலம். புத்திர பாக்கியம் நல்கும் தலம்.",
    "travel": "ராமநாதபுரத்திலிருந்து 10 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD089",
    "name_ta": "திருக்கூடல் (மதுரை)",
    "name_en": "Thirukkoodal",
    "district": "Madurai",
    "location": "Madurai",
    "god": "Koodal Azhagar",
    "goddess": "Maduravalli",
    "history": "மதுரை மாநகரின் மையத்தில் உள்ளது. அஷ்டாங்க விமானத்தின் மூன்று நிலைகளில் இறைவன் நின்ற, அமர்ந்த, கிடந்த கோலங்களில் உள்ளார்.",
    "travel": "மதுரை பெரியார் பேருந்து நிலையத்திற்கு மிக அருகில் உள்ளது."
  },
  {
    "id": "DD090",
    "name_ta": "திருமாலிருஞ்சோலை",
    "name_en": "Thirumaliruncholai (Azhagar Kovil)",
    "district": "Madurai",
    "location": "Azhagar Kovil",
    "god": "Kallazhagar",
    "goddess": "Sundaravalli",
    "history": "அழகர் மலை. சித்திரைத் திருவிழாவில் இறைவன் வைகை ஆற்றில் இறங்குவது உலகப்புகழ் பெற்றது.",
    "travel": "மதுரையிலிருந்து 20 கி.மீ. தொலைவில் உள்ளது. அடிக்கடி பேருந்து வசதி உண்டு."
  },
  {
    "id": "DD091",
    "name_ta": "திருமோகூர்",
    "name_en": "Thirumogur",
    "district": "Madurai",
    "location": "Thirumogur",
    "god": "Kalamega Perumal",
    "goddess": "Mohanavalli",
    "history": "அசுரர்களிடமிருந்து அமிர்தத்தை மீட்க இறைவன் மோகினி அவதாரம் எடுத்த தலம். சக்கரத்தாழ்வார் இங்கு விசேஷமானவர்.",
    "travel": "மதுரையிலிருந்து 12 கி.மீ. மேலூர் செல்லும் பாதையில் ஒத்தக்கடை அருகில் உள்ளது."
  },
  {
    "id": "DD092",
    "name_ta": "திருக்கண்ணபுரம் (திருக்கோளூர்)",
    "name_en": "Thirukolur",
    "district": "Thoothukudi",
    "location": "Alwarthirunagari",
    "god": "Vaitha Maanidhi Perumal",
    "goddess": "Kumudhavalli",
    "history": "நவதிருப்பதி தலங்களில் ஒன்று. குபேரன் இழந்த செல்வங்களை இத்தல இறைவனிடம் பெற்று மீண்டும் அடைந்ததாக வரலாறு.",
    "travel": "திருநெல்வேலி - திருச்செந்தூர் பாதையில் ஆழ்வார்திருநகரி அருகில் உள்ளது."
  },
  {
    "id": "DD093",
    "name_ta": "திருக்குருகூர் (ஆழ்வார்திருநகரி)",
    "name_en": "Thirukkurugur",
    "district": "Thoothukudi",
    "location": "Alwarthirunagari",
    "god": "Aadhinathan",
    "goddess": "Aadhinatha Valli",
    "history": "நம்மாழ்வார் அவதரித்த தலம். இங்குள்ள புளிய மரத்தின் பொந்திலேயே அவர் 16 ஆண்டுகள் யோகத்தில் இருந்தார்.",
    "travel": "திருநெல்வேலியிலிருந்து 30 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD094",
    "name_ta": "திருத்தலைச்சங்காடு (திருநாங்குறிச்சி)",
    "name_en": "Thirutholaivillimangalam",
    "district": "Thoothukudi",
    "location": "Irattai Tirupathi",
    "god": "Devapiran / Aravindalochanan",
    "goddess": "Karunthadankanni",
    "history": "இரட்டை திருப்பதி என்று அழைக்கப்படும் இரண்டு கோயில்கள். ஆத்ரேய முனிவர் யாகம் செய்த தலம்.",
    "travel": "ஆழ்வார்திருநகரியிலிருந்து 5 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD095",
    "name_ta": "ஸ்ரீவைகுண்டம்",
    "name_en": "Srivaikuntam",
    "district": "Thoothukudi",
    "location": "Srivaikuntam",
    "god": "Kalla Piran",
    "goddess": "Vaikundavalli",
    "history": "நவதிருப்பதியின் முதல் தலம். சூரிய ஒளி ஆண்டுக்கு இருமுறை மூலவர் மீது படுவது இக்கோயிலின் சிறப்பு.",
    "travel": "திருநெல்வேலியிலிருந்து 25 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD096",
    "name_ta": "திருப்புளிங்குடி",
    "name_en": "Thiruppulingudi",
    "district": "Thoothukudi",
    "location": "Srivaikuntam",
    "god": "Kaaisina Vendhan",
    "goddess": "Malarmagal",
    "history": "இறைவன் சயனக் கோலத்தில் உள்ளார். தொப்புள் கொடி தாமரை மூலமாகப் பிரம்மா காட்சி தருகிறார்.",
    "travel": "ஸ்ரீவைகுண்டத்திலிருந்து 2 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD097",
    "name_ta": "திருவரகுணமங்கை (நத்தம்)",
    "name_en": "Thiruvaragunamangai",
    "district": "Thoothukudi",
    "location": "Srivaikuntam",
    "god": "Vijayaasina Perumal",
    "goddess": "Varagunamangai தாயார்",
    "history": "ரோமச முனிவர் தவஞ்செய்த இடம். இறைவன் அமர்ந்த கோலத்தில் வீற்றிருக்கிறார்.",
    "travel": "ஸ்ரீவைகுண்டத்திலிருந்து 1 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD098",
    "name_ta": "திருப்புளிங்குடி (பெருங்குளம்)",
    "name_en": "Thirupperai",
    "district": "Thoothukudi",
    "location": "Thenthirupperai",
    "god": "Makara Nedunkuzhaikkadhan",
    "goddess": "Kuzhaikkadhavalli",
    "history": "இறைவன் தன் காதுகளில் மகர (மீன்) வடிவக் குண்டலங்களை அணிந்திருப்பதால் இப்பெயர் பெற்றார்.",
    "travel": "ஆழ்வார்திருநகரிக்கு அருகில் அமைந்துள்ளது."
  },
  {
    "id": "DD099",
    "name_ta": "திருக்குளந்தை",
    "name_en": "Thirukkulandhai",
    "district": "Thoothukudi",
    "location": "Perunkulam",
    "god": "Maayakoothan",
    "goddess": "Kulandhai Naachiyar",
    "history": "இறைவன் கருட வாகனத்தில் அமர்ந்து அரக்கனை அழித்த தலம். மார்கழி உற்சவம் விசேஷமானது.",
    "travel": "ஏரலிலிருந்து 5 கி.மீ. தொலைவில் உள்ளது."
  },
  {
    "id": "DD100",
    "name_ta": "திருக்குறுங்குடி",
    "name_en": "Thirukkurungudi",
    "district": "Tirunelveli",
    "location": "Thirukkurungudi",
    "god": "Azhagiya Nambi",
    "goddess": "Kurungudi Valli",
    "history": "இறைவன் ஒரு சீடனைப் போல ராமானுஜரிடம் உபதேசம் பெற்ற தலம். இங்கு 5 வகை 'நம்பி' சன்னதிகள் உள்ளன.",
    "travel": "நாங்குநேரியிலிருந்து 15 கி.மீ. தொலைவில் உள்ளது. மலையடிவாரத்தில் அமைந்துள்ளது."
  },
  {
    "id": "DD101",
    "name_ta": "திருச்சாளக்ராமம்",
    "name_en": "Thiruchaalagraamam (Muktinath)",
    "district": "Mustang",
    "location": "Nepal",
    "god": "Srimoorthi Perumal",
    "goddess": "Sridevi Naayaki",
    "history": "நேபாளத்தில் இமயமலைச் சாரலில் 12,500 அடி உயரத்தில் உள்ள தலம். இங்குள்ள கண்டகி நதியில் கிடைக்கும் புனிதமான கற்களே 'சாளக்கிராமம்'. இங்கு 108 புனித நீர் தாரைகள் உள்ளன.",
    "travel": "நேபாளம் பொக்காராவிலிருந்து ஜோம்சோம் சென்று, அங்கிருந்து வாடகை வாகனம் அல்லது குதிரை மூலம் அடையலாம். ஜூன் - செப்டம்பர் மழைக்காலத்தில் செல்வதைத் தவிர்க்கவும். இந்திய வாக்காளர் அட்டை அல்லது ஓட்டுநர் உரிமம் அவசியம்."
  },
  {
    "id": "DD102",
    "name_ta": "திருநைமிசாரண்யம்",
    "name_en": "Thirunaimisaranyam",
    "district": "Sitapur",
    "location": "Uttar Pradesh",
    "god": "Devaraja Perumal",
    "goddess": "Pundareegavalli",
    "history": "இறைவன் இங்கு காடாக (ஆரண்யம்) உருவெடுத்துக் காட்சி தருகிறார். சௌனகர் போன்ற முனிவர்கள் தவம் செய்த தலம். இங்குள்ள 'சக்ர தீர்த்தம்' மிகவும் புனிதமானது.",
    "travel": "லக்னோவிலிருந்து சுமார் 80 கி.மீ. தொலைவில் உள்ளது. இரயில் அல்லது பேருந்து மூலம் செல்லலாம்."
  },
  {
    "id": "DD103",
    "name_ta": "திருப்பிரிதி (ஜோஷிமத்)",
    "name_en": "Thiruppiridhai (Joshimath)",
    "district": "Chamoli",
    "location": "Uttarakhand",
    "god": "Paramapurushan",
    "goddess": "Parimalavalli",
    "history": "பத்ரிநாத் செல்லும் வழியில் அமைந்துள்ளது. குளிர்காலத்தில் பத்ரிநாத் கோயில் மூடப்படும் போது, அங்கிருக்கும் உற்சவர் இங்கு கொண்டுவரப்பட்டு வழிபாடு செய்யப்படுவார்.",
    "travel": "ரிஷிகேஷிலிருந்து சுமார் 250 கி.மீ. தொலைவில் மலைப்பாதையில் உள்ளது. ஹரித்வார் வழியாகச் செல்லலாம்."
  },
  {
    "id": "DD104",
    "name_ta": "திருப்பதரியாச்ரமம் (பத்ரிநாத்)",
    "name_en": "Thirubadhariyaasramam (Badrinath)",
    "district": "Chamoli",
    "location": "Uttarakhand",
    "god": "Badri Narayanan",
    "goddess": "Arvindhavalli",
    "history": "நாரண முனிவருக்காக இறைவன் பத்ரி (இலந்தை) மரமாகத் தாயார் நிழல் தர, தவம் செய்த தலம். இமயமலையில் உள்ள மிக முக்கியமான தலம்.",
    "travel": "ஹரித்வார் அல்லது ரிஷிகேஷிலிருந்து பேருந்து மூலம் செல்லலாம். மே முதல் அக்டோபர் வரை மட்டுமே திறந்திருக்கும். நவம்பர் - ஏப்ரல் மாதங்களில் பனிப்பொழிவு காரணமாக மூடப்படும்."
  },
  {
    "id": "DD105",
    "name_ta": "திருவேங்கடம் (திருப்பதி)",
    "name_en": "Thiruvengadam (Tirumala Tirupati)",
    "district": "Chittoor",
    "location": "Andhra Pradesh",
    "god": "Venkateswara",
    "goddess": "Padmavathi / Alarmelmangai",
    "history": "கலியுக வரதன் குடிகொண்டுள்ள மலை. ஏழு மலைகளின் அதிபதி. உலகிலேயே மிக அதிக பக்தர்கள் வந்து செல்லும் வைணவத் தலம்.",
    "travel": "திருப்பதியிலிருந்து மலைப்பாதையில் திருமலைக்குச் செல்லலாம். சென்னை மற்றும் பெங்களூரிலிருந்து மிக அருகில் உள்ளது. முன்கூட்டியே தரிசன டிக்கெட் பதிவு செய்வது அவசியம்."
  },
  {
    "id": "DD106",
    "name_ta": "திருஅயோத்தி",
    "name_en": "Thiru Ayoddhi",
    "district": "Ayodhya",
    "location": "Uttar Pradesh",
    "god": "Sri Ramar",
    "goddess": "Seetha Piratti",
    "history": "ராமபிரான் அவதரித்த தலம். சரயு நதிக்கரையில் அமைந்துள்ள புனித நகரம். ஏழு முக்தி தரும் நகரங்களில் முதன்மையானது.",
    "travel": "லக்னோவிலிருந்து 135 கி.மீ. தொலைவில் உள்ளது. இரயில் மற்றும் விமான வசதி உள்ளது."
  },
  {
    "id": "DD107",
    "name_ta": "திருப்பாற்கடல்",
    "name_en": "Thiruppaarkadal (Celestial)",
    "district": "Celestial",
    "location": "Celestial",
    "god": "Ksheerabdhi Sayanan",
    "goddess": "Kadalmagal Naayaki",
    "history": "திருமால் ஆதிசேஷன் மீது யோக நித்திரையில் ஆழ்ந்திருக்கும் பாற்கடல். இது வியூக நிலையில் உள்ள தலம்.",
    "travel": "விண்ணுலகத் தலம்; மானுடப் பயணம் சாத்தியமில்லை."
  },
  {
    "id": "DD108",
    "name_ta": "திருப் பரமபதம்",
    "name_en": "ThirupParamapadham (Celestial)",
    "district": "Celestial",
    "location": "Celestial",
    "god": "Paramapada Nathan",
    "goddess": "Periyananaayaki",
    "history": "வைகுண்டம். பிறவிப் பெருங்கடல் நீந்திய முக்தி பெற்ற ஆன்மாக்கள் அடையும் இறுதித் தலம். இது பரத்துவ நிலையில் உள்ள தலம்.",
    "travel": "விண்ணுலகத் தலம்; ஆன்மீக ரீதியானது."
  }
];